CREATE SCHEMA IF NOT EXISTS deap ;
USE deap ;

CREATE TABLE IF NOT EXISTS PRODUCTOS (
  CODIGOPRODUCTO VARCHAR(15) NOT NULL,
  NOMBRE VARCHAR(70) NOT NULL,
  GAMA VARCHAR(50),
  DIMENSIONES VARCHAR(25)  DEFAULT NULL,
  PROVEEDOR VARCHAR(50)  DEFAULT NULL,
  DESCRIPCION VARCHAR(600)  DEFAULT NULL,
  CANTIDADENSTOCK INT ,
  PRECIOVENTA INT ,
  PRECIOPROVEEDOR INT DEFAULT NULL,
  PRIMARY KEY (CODIGOPRODUCTO));

Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('11679','Sierra de Poda 400MM','Herramientas','0,258','HiperGarden Tools',15,14,11);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('21636','Pala','Herramientas','0,156','HiperGarden Tools',15,14,13);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('22225','Rastrillo de Jardín','Herramientas','1,064','HiperGarden Tools',15,12,11);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('30310','Azadón','Herramientas','0,168','HiperGarden Tools',15,12,11);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-001','Ajedrea','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-002','Lavándula Dentata','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-003','Mejorana','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-004','Melissa ','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-005','Mentha Sativa','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-14','Calamondin Mini','Frutales',null,'Frutales Talavera S.A',15,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-15','Calamondin Copa ','Frutales',null,'Frutales Talavera S.A',15,25,20);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-16','Calamondin Copa EXTRA Con FRUTA','Frutales','100-120','Frutales Talavera S.A',15,45,36);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-17','Rosal bajo 1Âª -En maceta-inicio brotación','Frutales',null,'Frutales Talavera S.A',15,2,1);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-18','ROSAL TREPADOR','Frutales',null,'Frutales Talavera S.A',350,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-19','Camelia Blanco, Chrysler Rojo, Soraya Naranja, ','Frutales',null,'NaranjasValencianas.com',350,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-2','Naranjo -Plantón joven 1 año injerto','Frutales',null,'NaranjasValencianas.com',15,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-20','Landora Amarillo, Rose Gaujard bicolor blanco-rojo','Frutales',null,'Frutales Talavera S.A',350,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-21','Kordes Perfect bicolor rojo-amarillo, Roundelay rojo fuerte','Frutales',null,'Frutales Talavera S.A',350,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-22','Pitimini rojo','Frutales',null,'Frutales Talavera S.A',350,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-23','Rosal copa ','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-24','Albaricoquero Corbato','Frutales',null,'Melocotones de Cieza S.A.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-006','Petrosilium Hortense (Peregil)','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-007','Salvia Mix','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-008','Thymus Citriodra (Tomillo limón)','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-009','Thymus Vulgaris','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('AR-010','Santolina Chamaecyparys','Aromáticas','15-20','Murcia Seasons',140,1,0);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-1','Expositor Cítricos Mix','Frutales','100-120','Frutales Talavera S.A',15,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-10','Limonero 2 años injerto','Frutales',null,'NaranjasValencianas.com',15,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-100','Nectarina','Frutales','8/10','Frutales Talavera S.A',50,11,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-101','Nogal','Frutales','8/10','Frutales Talavera S.A',50,13,10);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-102','Olea-Olivos','Frutales','8/10','Frutales Talavera S.A',50,18,14);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-103','Olea-Olivos','Frutales','10/12','Frutales Talavera S.A',50,25,20);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-104','Olea-Olivos','Frutales','12/4','Frutales Talavera S.A',50,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-105','Olea-Olivos','Frutales','14/16','Frutales Talavera S.A',50,70,56);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-106','Peral','Frutales','8/10','Frutales Talavera S.A',50,11,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-107','Peral','Frutales','10/12','Frutales Talavera S.A',50,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-108','Peral','Frutales','12/14','Frutales Talavera S.A',50,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-11','Limonero 30/40','Frutales',null,'NaranjasValencianas.com',15,100,80);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-12','Kunquat ','Frutales',null,'NaranjasValencianas.com',15,21,16);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-13','Kunquat  EXTRA con FRUTA','Frutales','150-170','NaranjasValencianas.com',15,57,45);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-45','Melocotonero Amarillo de Agosto','Frutales',null,'Melocotones de Cieza S.A.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-46','Melocotonero Federica','Frutales',null,'Melocotones de Cieza S.A.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-47','Melocotonero Paraguayo','Frutales',null,'Melocotones de Cieza S.A.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-48','Nogal Común','Frutales',null,'Frutales Talavera S.A',400,9,7);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-49','Parra Uva de Mesa','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-5','Mandarino -Plantón joven','Frutales',null,'Frutales Talavera S.A',15,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-50','Peral Castell','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-51','Peral Williams','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-52','Peral Conference','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-53','Peral Blanq. de Aranjuez','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-54','Níspero Tanaca','Frutales',null,'Frutales Talavera S.A',400,9,7);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-63','Cerezo','Frutales','8/10','Jerte Distribuciones S.L.',300,11,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-64','Cerezo','Frutales','10/12','Jerte Distribuciones S.L.',15,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-65','Cerezo','Frutales','12/14','Jerte Distribuciones S.L.',200,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-66','Cerezo','Frutales','14/16','Jerte Distribuciones S.L.',50,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-67','Cerezo','Frutales','16/18','Jerte Distribuciones S.L.',50,70,56);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-68','Cerezo','Frutales','18/20','Jerte Distribuciones S.L.',50,80,64);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-69','Cerezo','Frutales','20/25','Jerte Distribuciones S.L.',50,91,72);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-7','Mandarino calibre 8/10','Frutales',null,'Frutales Talavera S.A',15,29,23);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-70','Ciruelo','Frutales','8/10','Frutales Talavera S.A',50,11,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-71','Ciruelo','Frutales','10/12','Frutales Talavera S.A',50,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-72','Ciruelo','Frutales','12/14','Frutales Talavera S.A',50,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-73','Granado','Frutales','8/10','Frutales Talavera S.A',50,13,10);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-74','Granado','Frutales','10/12','Frutales Talavera S.A',50,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-75','Granado','Frutales','12/14','Frutales Talavera S.A',50,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-76','Granado','Frutales','14/16','Frutales Talavera S.A',50,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-77','Granado','Frutales','16/18','Frutales Talavera S.A',50,70,56);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-78','Higuera','Frutales','8/10','Frutales Talavera S.A',50,15,12);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-79','Higuera','Frutales','10/12','Frutales Talavera S.A',50,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-55','Olivo Cipresino','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-56','Nectarina','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-57','Kaki Rojo Brillante','Frutales',null,'NaranjasValencianas.com',400,9,7);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-58','Albaricoquero','Frutales','8/10','Melocotones de Cieza S.A.',200,11,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-59','Albaricoquero','Frutales','10/12','Melocotones de Cieza S.A.',200,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-6','Mandarino 2 años injerto','Frutales',null,'Frutales Talavera S.A',15,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-60','Albaricoquero','Frutales','12/14','Melocotones de Cieza S.A.',200,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-61','Albaricoquero','Frutales','14/16','Melocotones de Cieza S.A.',200,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-62','Albaricoquero','Frutales','16/18','Melocotones de Cieza S.A.',200,70,56);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-25','Albaricoquero Moniqui','Frutales',null,'Melocotones de Cieza S.A.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-26','Albaricoquero Kurrot','Frutales',null,'Melocotones de Cieza S.A.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-27','Cerezo Burlat','Frutales',null,'Jerte Distribuciones S.L.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-28','Cerezo Picota','Frutales',null,'Jerte Distribuciones S.L.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-29','Cerezo Napoleón','Frutales',null,'Jerte Distribuciones S.L.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-3','Naranjo 2 años injerto','Frutales',null,'NaranjasValencianas.com',15,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-30','Ciruelo R. Claudia Verde   ','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-31','Ciruelo Santa Rosa','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-32','Ciruelo Golden Japan','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-33','Ciruelo Friar','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-34','Ciruelo Reina C. De Ollins','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-35','Ciruelo Claudia Negra','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-36','Granado Mollar de Elche','Frutales',null,'Frutales Talavera S.A',400,9,7);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-37','Higuera Napolitana','Frutales',null,'Frutales Talavera S.A',400,9,7);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-38','Higuera Verdal','Frutales',null,'Frutales Talavera S.A',400,9,7);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-39','Higuera Breva','Frutales',null,'Frutales Talavera S.A',400,9,7);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-4','Naranjo calibre 8/10','Frutales',null,'NaranjasValencianas.com',15,29,23);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-40','Manzano Starking Delicious','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-41','Manzano Reineta','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-42','Manzano Golden Delicious','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-43','Membrillero Gigante de Wranja','Frutales',null,'Frutales Talavera S.A',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-44','Melocotonero Spring Crest','Frutales',null,'Melocotones de Cieza S.A.',400,8,6);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-104','Mimosa Semilla Cyanophylla    ','Ornamentales','200-225','Viveros EL OASIS',100,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-105','Mimosa Semilla Espectabilis  ','Ornamentales','160-170','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-106','Mimosa Semilla Longifolia   ','Ornamentales','200-225','Viveros EL OASIS',100,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-107','Mimosa Semilla Floribunda 4 estaciones','Ornamentales','120-140','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-108','Abelia Floribunda','Ornamentales','35-45','Viveros EL OASIS',100,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-109','Callistemom (Mix)','Ornamentales','35-45','Viveros EL OASIS',100,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-110','Callistemom (Mix)','Ornamentales','40-60','Viveros EL OASIS',100,2,1);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-111','Corylus Avellana Contorta','Ornamentales','35-45','Viveros EL OASIS',100,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-112','Escallonia (Mix)','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-113','Evonimus Emerald Gayeti','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-114','Evonimus Pulchellus','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-115','Forsytia Intermedia Lynwood','Ornamentales','35-45','Viveros EL OASIS',120,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-116','Hibiscus Syriacus  Diana -Blanco Puro','Ornamentales','35-45','Viveros EL OASIS',120,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-117','Hibiscus Syriacus  Helene -Blanco-C.rojo','Ornamentales','35-45','Viveros EL OASIS',120,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-118','Hibiscus Syriacus Pink Giant Rosa','Ornamentales','35-45','Viveros EL OASIS',120,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-119','Laurus Nobilis Arbusto - Ramificado Bajo','Ornamentales','40-50','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-120','Lonicera Nitida ','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-121','Lonicera Nitida Maigrum','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-122','Lonicera Pileata','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-123','Philadelphus Virginal','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-124','Prunus pisardii  ','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-125','Viburnum Tinus Eve Price','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-126','Weigelia Bristol Ruby','Ornamentales','35-45','Viveros EL OASIS',120,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-127','Camelia japonica','Ornamentales','40-60','Viveros EL OASIS',50,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-128','Camelia japonica ejemplar','Ornamentales','200-250','Viveros EL OASIS',50,98,78);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-129','Camelia japonica ejemplar','Ornamentales','250-300','Viveros EL OASIS',50,110,88);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-130','Callistemom COPA','Ornamentales','110/120','Viveros EL OASIS',50,18,14);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-131','Leptospermum formado PIRAMIDE','Ornamentales','80-100','Viveros EL OASIS',50,18,14);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-132','Leptospermum COPA','Ornamentales','110/120','Viveros EL OASIS',50,18,14);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-133','Nerium oleander-CALIDAD GARDEN','Ornamentales','40-45','Viveros EL OASIS',50,2,1);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-134','Nerium Oleander Arbusto GRANDE','Ornamentales','160-200','Viveros EL OASIS',100,38,30);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-135','Nerium oleander COPA  Calibre 6/8','Ornamentales','50-60','Viveros EL OASIS',100,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-136','Nerium oleander ARBOL Calibre 8/10','Ornamentales','225-250','Viveros EL OASIS',100,18,14);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-137','ROSAL TREPADOR','Ornamentales',null,'Viveros EL OASIS',100,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-138','Camelia Blanco, Chrysler Rojo, Soraya Naranja, ','Ornamentales',null,'Viveros EL OASIS',100,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-139','Landora Amarillo, Rose Gaujard bicolor blanco-rojo','Ornamentales',null,'Viveros EL OASIS',100,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-140','Kordes Perfect bicolor rojo-amarillo, Roundelay rojo fuerte','Ornamentales',null,'Viveros EL OASIS',100,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-141','Pitimini rojo','Ornamentales',null,'Viveros EL OASIS',100,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-142','Solanum Jazminoide','Ornamentales','150-160','Viveros EL OASIS',100,2,1);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-143','Wisteria Sinensis  azul, rosa, blanca','Ornamentales',null,'Viveros EL OASIS',100,9,7);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-144','Wisteria Sinensis INJERTADAS DECÃ“','Ornamentales','140-150','Viveros EL OASIS',100,12,9);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-145','Bougamvillea Sanderiana Tutor','Ornamentales','80-100','Viveros EL OASIS',100,2,1);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-146','Bougamvillea Sanderiana Tutor','Ornamentales','125-150','Viveros EL OASIS',100,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-147','Bougamvillea Sanderiana Tutor','Ornamentales','180-200','Viveros EL OASIS',100,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-148','Bougamvillea Sanderiana Espaldera','Ornamentales','45-50','Viveros EL OASIS',100,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-149','Bougamvillea Sanderiana Espaldera','Ornamentales','140-150','Viveros EL OASIS',100,17,13);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-150','Bougamvillea roja, naranja','Ornamentales','110-130','Viveros EL OASIS',100,2,1);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-151','Bougamvillea Sanderiana, 3 tut. piramide','Ornamentales',null,'Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-152','Expositor Árboles clima continental','Ornamentales','170-200','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-153','Expositor Árboles clima mediterráneo','Ornamentales','170-200','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-154','Expositor Árboles borde del mar','Ornamentales','170-200','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-155','Acer Negundo  ','Ornamentales','200-225','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-156','Acer platanoides  ','Ornamentales','200-225','Viveros EL OASIS',100,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-157','Acer Pseudoplatanus ','Ornamentales','200-225','Viveros EL OASIS',100,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-158','Brachychiton Acerifolius  ','Ornamentales','200-225','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-159','Brachychiton Discolor  ','Ornamentales','200-225','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-160','Brachychiton Rupestris','Ornamentales','170-200','Viveros EL OASIS',100,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-161','Cassia Corimbosa  ','Ornamentales','200-225','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-162','Cassia Corimbosa ','Ornamentales','200-225','Viveros EL OASIS',100,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-163','Chitalpa Summer Bells   ','Ornamentales','200-225','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-164','Erytrina Kafra','Ornamentales','170-180','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-165','Erytrina Kafra','Ornamentales','200-225','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-166','Eucalyptus Citriodora  ','Ornamentales','170-200','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-167','Eucalyptus Ficifolia  ','Ornamentales','170-200','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-168','Eucalyptus Ficifolia   ','Ornamentales','200-225','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-169','Hibiscus Syriacus  Var. Injertadas 1 Tallo ','Ornamentales','170-200','Viveros EL OASIS',80,12,9);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-170','Lagunaria Patersonii  ','Ornamentales','140-150','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-171','Lagunaria Patersonii   ','Ornamentales','200-225','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-172','Lagunaria patersonii  calibre 8/10','Ornamentales','200-225','Viveros EL OASIS',80,18,14);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-173','Morus Alba  ','Ornamentales','200-225','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-174','Morus Alba  calibre 8/10','Ornamentales','200-225','Viveros EL OASIS',80,18,14);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-175','Platanus Acerifolia   ','Ornamentales','200-225','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-176','Prunus pisardii  ','Ornamentales','200-225','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-177','Robinia Pseudoacacia Casque Rouge   ','Ornamentales','200-225','Viveros EL OASIS',80,15,12);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-178','Salix Babylonica  Pendula  ','Ornamentales','170-200','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-179','Sesbania Punicea   ','Ornamentales','170-200','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-180','Tamarix  Ramosissima Pink Cascade   ','Ornamentales','170-200','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-181','Tamarix  Ramosissima Pink Cascade   ','Ornamentales','200-225','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-182','Tecoma Stands   ','Ornamentales','200-225','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-183','Tecoma Stands  ','Ornamentales','200-225','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-184','Tipuana Tipu  ','Ornamentales','170-200','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-185','Pleioblastus distichus-Bambú enano','Ornamentales','15-20','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-186','Sasa palmata ','Ornamentales','20-30','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-187','Sasa palmata ','Ornamentales','40-45','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-188','Sasa palmata ','Ornamentales','50-60','Viveros EL OASIS',80,25,20);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-189','Phylostachys aurea','Ornamentales','180-200','Viveros EL OASIS',80,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-190','Phylostachys aurea','Ornamentales','250-300','Viveros EL OASIS',80,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-191','Phylostachys Bambusa Spectabilis','Ornamentales','180-200','Viveros EL OASIS',80,24,19);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-192','Phylostachys biseti','Ornamentales','160-170','Viveros EL OASIS',80,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-193','Phylostachys biseti','Ornamentales','160-180','Viveros EL OASIS',80,20,16);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-194','Pseudosasa japonica (Metake)','Ornamentales','225-250','Viveros EL OASIS',80,20,16);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-195','Pseudosasa japonica (Metake) ','Ornamentales','30-40','Viveros EL OASIS',80,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-196','Cedrus Deodara ','Ornamentales','80-100','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-197','Cedrus Deodara Feeling Blue Novedad','Ornamentales','rastrero','Viveros EL OASIS',80,12,9);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-198','Juniperus chinensis Blue Alps','Ornamentales','20-30','Viveros EL OASIS',80,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-199','Juniperus Chinensis Stricta','Ornamentales','20-30','Viveros EL OASIS',80,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-200','Juniperus horizontalis Wiltonii','Ornamentales','20-30','Viveros EL OASIS',80,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-201','Juniperus squamata Blue Star','Ornamentales','20-30','Viveros EL OASIS',80,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-202','Juniperus x media Phitzeriana verde','Ornamentales','20-30','Viveros EL OASIS',80,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-203','Pinus Canariensis','Ornamentales','80-100','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-204','Pinus Halepensis','Ornamentales','160-180','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-205','Pinus Pinea -Pino Piñonero','Ornamentales','70-80','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-206','Thuja Esmeralda ','Ornamentales','80-100','Viveros EL OASIS',80,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-207','Tuja Occidentalis Woodwardii','Ornamentales','20-30','Viveros EL OASIS',80,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-208','Tuja orientalis Aurea nana','Ornamentales','20-30','Viveros EL OASIS',80,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-209','Archontophoenix Cunninghamiana','Ornamentales','80 - 100','Viveros EL OASIS',80,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-210','Beucarnea Recurvata','Ornamentales','130  - 150','Viveros EL OASIS',2,39,31);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-211','Beucarnea Recurvata','Ornamentales','180 - 200','Viveros EL OASIS',5,59,47);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-212','Bismarckia Nobilis','Ornamentales','200 - 220','Viveros EL OASIS',4,217,173);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-213','Bismarckia Nobilis','Ornamentales','240 - 260','Viveros EL OASIS',4,266,212);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-214','Brahea Armata','Ornamentales','45 - 60','Viveros EL OASIS',0,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-215','Brahea Armata','Ornamentales','120 - 140','Viveros EL OASIS',100,112,89);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-216','Brahea Edulis','Ornamentales','80 - 100','Viveros EL OASIS',100,19,15);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-217','Brahea Edulis','Ornamentales','140 - 160','Viveros EL OASIS',100,64,51);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-218','Butia Capitata','Ornamentales','70 - 90','Viveros EL OASIS',100,25,20);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-219','Butia Capitata','Ornamentales','90 - 110','Viveros EL OASIS',100,29,23);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-220','Butia Capitata','Ornamentales','90 - 120','Viveros EL OASIS',100,36,28);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-221','Butia Capitata','Ornamentales','85 - 105','Viveros EL OASIS',100,59,47);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-222','Butia Capitata','Ornamentales','130 - 150','Viveros EL OASIS',100,87,69);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-223','Chamaerops Humilis','Ornamentales','40 - 45','Viveros EL OASIS',100,4,3);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-224','Chamaerops Humilis','Ornamentales','50 - 60','Viveros EL OASIS',100,7,5);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-225','Chamaerops Humilis','Ornamentales','70 - 90','Viveros EL OASIS',100,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-226','Chamaerops Humilis','Ornamentales','115 - 130','Viveros EL OASIS',100,38,30);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-227','Chamaerops Humilis','Ornamentales','130 - 150','Viveros EL OASIS',100,64,51);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-228','Chamaerops Humilis Cerifera','Ornamentales','70 - 80','Viveros EL OASIS',100,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-229','Chrysalidocarpus Lutescens -ARECA','Ornamentales','130 - 150','Viveros EL OASIS',100,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-8','Limonero -Plantón joven','Frutales',null,'NaranjasValencianas.com',15,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-80','Higuera','Frutales','12/14','Frutales Talavera S.A',50,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-81','Higuera','Frutales','14/16','Frutales Talavera S.A',50,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-82','Higuera','Frutales','16/18','Frutales Talavera S.A',50,70,56);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-83','Higuera','Frutales','18/20','Frutales Talavera S.A',50,80,64);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-84','Kaki','Frutales','8/10','NaranjasValencianas.com',50,13,10);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-85','Kaki','Frutales','16/18','NaranjasValencianas.com',50,70,56);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-86','Manzano','Frutales','8/10','Frutales Talavera S.A',50,11,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-87','Manzano','Frutales','10/12','Frutales Talavera S.A',50,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-88','Manzano','Frutales','12/14','Frutales Talavera S.A',50,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-89','Manzano','Frutales','14/16','Frutales Talavera S.A',50,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-9','Limonero calibre 8/10','Frutales',null,'NaranjasValencianas.com',15,29,23);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-90','Níspero','Frutales','16/18','Frutales Talavera S.A',50,70,56);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-91','Níspero','Frutales','18/20','Frutales Talavera S.A',50,80,64);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-92','Melocotonero','Frutales','8/10','Melocotones de Cieza S.A.',50,11,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-93','Melocotonero','Frutales','10/12','Melocotones de Cieza S.A.',50,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-94','Melocotonero','Frutales','12/14','Melocotones de Cieza S.A.',50,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-95','Melocotonero','Frutales','14/16','Melocotones de Cieza S.A.',50,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-96','Membrillero','Frutales','8/10','Frutales Talavera S.A',50,11,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-97','Membrillero','Frutales','10/12','Frutales Talavera S.A',50,22,17);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-98','Membrillero','Frutales','12/14','Frutales Talavera S.A',50,32,25);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('FR-99','Membrillero','Frutales','14/16','Frutales Talavera S.A',50,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-001','Arbustos Mix Maceta','Ornamentales','40-60','Valencia Garden Service',25,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-100','Mimosa Injerto CLASICA Dealbata ','Ornamentales','100-110','Viveros EL OASIS',100,12,9);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-101','Expositor Mimosa Semilla Mix','Ornamentales','170-200','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-102','Mimosa Semilla Bayleyana  ','Ornamentales','170-200','Viveros EL OASIS',100,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-103','Mimosa Semilla Bayleyana   ','Ornamentales','200-225','Viveros EL OASIS',100,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-230','Cordyline Australis -DRACAENA','Ornamentales','190 - 210','Viveros EL OASIS',100,38,30);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-231','Cycas Revoluta','Ornamentales','55 - 65','Viveros EL OASIS',100,15,12);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-232','Cycas Revoluta','Ornamentales','80 - 90','Viveros EL OASIS',100,34,27);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-233','Dracaena Drago','Ornamentales','60 - 70','Viveros EL OASIS',1,13,10);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-234','Dracaena Drago','Ornamentales','130 - 150','Viveros EL OASIS',2,64,51);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-235','Dracaena Drago','Ornamentales','150 - 175','Viveros EL OASIS',2,92,73);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-236','Jubaea Chilensis','Ornamentales',null,'Viveros EL OASIS',100,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-237','Livistonia Australis','Ornamentales','100 - 125','Viveros EL OASIS',50,19,15);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-238','Livistonia Decipiens','Ornamentales','90 - 110','Viveros EL OASIS',50,19,15);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-239','Livistonia Decipiens','Ornamentales','180 - 200','Viveros EL OASIS',50,49,39);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-240','Phoenix Canariensis','Ornamentales','110 - 130','Viveros EL OASIS',50,6,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-241','Phoenix Canariensis','Ornamentales','180 - 200','Viveros EL OASIS',50,19,15);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-242','Rhaphis Excelsa','Ornamentales','80 - 100','Viveros EL OASIS',50,21,16);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-243','Rhaphis Humilis','Ornamentales','150- 170','Viveros EL OASIS',50,64,51);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-244','Sabal Minor','Ornamentales','60 - 75','Viveros EL OASIS',50,11,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-245','Sabal Minor','Ornamentales','120 - 140','Viveros EL OASIS',50,34,27);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-246','Trachycarpus Fortunei','Ornamentales','90 - 105','Viveros EL OASIS',50,18,14);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-247','Trachycarpus Fortunei','Ornamentales','250-300','Viveros EL OASIS',2,462,369);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-248','Washingtonia Robusta','Ornamentales','60 - 70','Viveros EL OASIS',15,3,2);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-249','Washingtonia Robusta','Ornamentales','130 - 150','Viveros EL OASIS',15,5,4);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-250','Yucca Jewel','Ornamentales','80 - 105','Viveros EL OASIS',15,10,8);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-251','Zamia Furfuracaea','Ornamentales','90 - 110','Viveros EL OASIS',15,168,134);
Insert into PRODUCTOS (CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) values ('OR-99','Mimosa DEALBATA Gaulois Astier  ','Ornamentales','200-225','Viveros EL OASIS',100,14,11);

CREATE TABLE IF NOT EXISTS alumnos (
  expediente VARCHAR(15) NOT NULL,
  nombre VARCHAR(70) NOT NULL,
  curso INT DEFAULT NULL,
  PRIMARY KEY (expediente));
  
Insert into alumnos (expediente,nombre,curso) 
values ('exp1','Alumno 1','1')
,('exp2','Alumno 2','2')
,('exp3','Alumno 3','1')
,('exp4','Alumno 4','2')
,('exp5','Alumno 5','1')
,('exp6','Alumno 6','2')
,('exp7','Alumno 7','1')
,('exp8','Alumno 8','1')
,('exp9','Alumno 9','2')
,('exp10','Alumno 10','1')
,('exp11','Alumno 10','1')
,('exp12','Alumno 10','1')
;